name: IntelliDoors
version: 1.2.0
description: Open and close doors with ease.
author: moltendorf
website: http://dev.bukkit.org/server-mods/moltendorf-intellidoors/
main: net.moltendorf.Bukkit.IntelliDoors.IntelliDoors
