package com.moltendorf.bukkit.intellidoors;

import org.bukkit.event.player.PlayerInteractEvent;

/**
 * Handles events generated by players interacting with blocks.
 *
 * @author moltendorf
 */
class Listener_Interact_Monitor extends Listener_Interact {
	@Override
	public void onPlayerInteract(final PlayerInteractEvent event) {
		// Fail if the event was cancelled, or if there is no block.
		if (event.isCancelled() || !event.hasBlock()) {
			return;
		}

		final Handler handler = getHandler(event.getClickedBlock());

		// Fail if we didn't get a door set.
		if (handler == null) {
			return;
		}

		handler.onInteract();
	}
}
