package com.moltendorf.bukkit.intellidoors;

import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.event.player.PlayerListener;

/**
 * Handles events generated by players interacting with blocks.
 *
 * @author moltendorf
 */
class Listener_Interact extends PlayerListener implements Listener {
	protected Handler getHandler(final Block block) {
		// Get the material of block that was passed.
		final Material material = block.getType();

		// Check that the material of the block is one of the types we handle.
		switch (material) {
			case FENCE_GATE:
			case TRAP_DOOR:
			case WOODEN_DOOR:
				// Finally, get our door set.
				return Door.Get(material, block, this);
		}

		return null;
	}

	@Override
	public Handler make(final Set_FenceGate set, final boolean open) {
		return new Handler(set, open);
	}

	@Override
	public Handler make(final Set_Trap set, final boolean open) {
		return new Handler(set, open);
	}

	@Override
	public Handler make(final Material material, final Set_Door_Single set, final boolean open) {
		return new Handler(material, set, open);
	}

	@Override
	public Handler make(final Material material, final Set_Door_Double set, final boolean open, final boolean side) {
		return new Handler_Interact_Double(material, set, open, side);
	}

	@Override
	public void onPlayerInteract(final PlayerInteractEvent event) {
		// Fail if the event was cancelled, or if there is no block.
		if (event.isCancelled() || !event.hasBlock()) {
			return;
		}

		final Handler handler = getHandler(event.getClickedBlock());

		// Fail if we didn't get a door set.
		if (handler == null) {
			return;
		}

		if (handler.busy()) {
			event.setCancelled(true);
		}
	}
}
