package com.moltendorf.bukkit.intellidoors;

import org.bukkit.Material;
import org.bukkit.event.block.BlockRedstoneEvent;

/**
 * Handles events generated by redstone events.
 *
 * @author moltendorf
 */
class Listener_Redstone extends Listener_Physics {
	@Override
	public Handler make(final Material material, final Set_Door_Double set, final boolean open, final boolean side) {
		return new Handler_Redstone_Double(material, set, side);
	}

	@Override
	public void onBlockRedstoneChange(final BlockRedstoneEvent event) {
		final Handler handler = getHandler(event.getBlock());

		// Fail if we didn't get a door set.
		if (handler == null) {
			return;
		}

		event.setNewCurrent(handler.getPower());
	}
}
